Add domain to build_client
open-feature/ruby-sdk pull request #109
Opened 2024-03-26 21:26 UTC by grepfruit19

## This PR

- Adds domain lookup to build_client

### Related Issues

Fixes #108 

### How to test

Instantiate the library with and without a `domain` for its provider.

2024-03-27 12:32 UTC, beeme1mr reviewed
Could you please add some tests and update the readme?

@maxveldink, how would you feel about removing the name argument entirely? It would be a breaking change but help us avoid technical debut as we move towards a 1.0 release.

2024-03-27 12:32 UTC, beeme1mr commented on lib/open_feature/sdk/api.rb
>          client_options = Metadata.new(name: name, version: version).freeze
Could you please also add domain to the metadata?

2024-03-27 16:19 UTC, grepfruit19 commented on lib/open_feature/sdk/client.rb
> +      attr_reader :metadata, :provider
I exposed the provider here. This was sort of for testing purposes, but using this library in general, I've found that it would have been helpful to have access to the provider in other cases.

2024-03-27 16:23 UTC, grepfruit19 commented
@beeme1mr @maxveldink 

I added some tests.

I didn't want to change the behavior of the library too much, but maybe trying to instantiate a client against a domain that doesn't exist should throw or something, I feel like instantiating with the NoOp provider is unexpected behavior.

2024-03-27 17:57 UTC, maxveldink commented
Thanks for fixing this @grepfruit19! Definitely, an oversight I had when I was trying to convert us over from `name` to `domain.` I agree that we should completely drop `name` wherever it's used (pre-1.0, I don't think we should have the idea of "legacy" fields; we should attempt to match the spec as close as possible).

Further, I think dropping `version` makes sense as well. I think @technicalpickles or @josecolella could explain why it was added, but it's not a part of the current specification and might confuse users. One other thing to think through; I don't think we can reuse `Metadata` for both `Provider`s and `Client`s; they have different required fields. I'd be up for either dropping that class in favor of a simple hash for now or introducing `ClientMetadata` and `ProviderMetadata` classes to explicitly state the keys we allow.

Let me know if that's enough to go on, or if you need more direction here. This will definitely be a breaking change.

2024-03-27 18:04 UTC, grepfruit19 commented
Sounds good, I can add the changes to drop `name` and `version if we're in agreement. I'd rather keep this PR limited in scope as far as adding the `ClientMetadata` and `ProviderMetadata` classes however, so I'd prefer not to add those changes in this PR.

2024-03-27 20:02 UTC, grepfruit19 commented
@beeme1mr @maxveldink 

I've removed `name` from the library, I think things should be good to go now. I've held off on removing `version` so that y'all can make a separate PR since it seems like that has some further discussion to be had.

Let me know if there's anything else to be done!

2024-03-28 00:30 UTC, maxveldink requested changes
We need to back out the changes to the `Metadata#name` field and keep that the same. The changes to `build_client` are good though 👍🏻

2024-03-28 00:30 UTC, maxveldink commented on README.md
> +client = OpenFeature::SDK.build_client()
suggestion(non-blocking):

```suggestion
client = OpenFeature::SDK.build_client
```

2024-03-28 00:30 UTC, maxveldink commented on lib/open_feature/sdk/api.rb
> +        Client.new(provider: active_provider, client_options: client_options, context: context)
suggestion(non-blocking): If we use hash omission, we should be consistent and do it everywhere. 

```suggestion
        client_options = Metadata.new(version, domain:).freeze

        active_provider = provider(domain:).nil? ? Provider::NoOpProvider.new : provider(domain:)

        Client.new(provider: active_provider, client_options:, context:)
```

2024-03-28 00:30 UTC, maxveldink commented on lib/open_feature/sdk/metadata.rb
Confusingly, the `name` here actually refers to the [Provider name](https://openfeature.dev/specification/sections/providers#requirement-211) which is _not_ the same as the client `name` that was replaced by `domain`. We don't need to change anything about metadata and the default provider naming. Sorry if that was unclear 😞

2024-03-28 00:30 UTC, maxveldink commented on lib/open_feature/sdk/client.rb
> +      attr_reader :metadata, :provider
I _think_ having read access to the provider is fine here. I want to double-check with someone else if they think this is potentially circumventing the spec.

cc @josecolella @technicalpickles @beeme1mr

2024-03-28 14:31 UTC, maxveldink submitted a review, later dismissed
Going to wait a little while longer for others to review as well, will merge in by EoD

2024-03-29 01:11 UTC, beeme1mr submitted a review, later dismissed
Approved, but please double-check if exposing the provider is required before merging.

2024-03-29 01:11 UTC, beeme1mr commented on lib/open_feature/sdk/api.rb
> +        active_provider = provider(domain:).nil? ? Provider::NoOpProvider.new : provider(domain:)
This is fine for now but eventually, the Ruby SDK should allow for providers to be bound to existing clients. That's how other SDKs behave but definitely adds to the complexity.

2024-03-29 01:11 UTC, beeme1mr commented on lib/open_feature/sdk/client.rb
> +      attr_reader :metadata, :provider
The provider is not intended to be used directly by a user. I would avoid exposing it here if possible. What use cases are you trying to support?

FYI @toddbaert.

2024-03-29 13:47 UTC, grepfruit19 commented
@beeme1mr Is there a good way to check what provider a client is using then?

2024-03-29 14:02 UTC, beeme1mr commented
> @beeme1mr Is there a good way to check what provider a client is using then?

Hey @grepfruit19, you can use the provider metadata on the client. [Here's](https://github.com/open-feature/js-sdk/blob/main/packages/server/src/client/open-feature-client.ts#L62) how we implemented that in the JS SDK.

If you're interested, this is how we passed the [provider reference](https://github.com/open-feature/js-sdk/blob/main/packages/server/src/client/open-feature-client.ts#L44-L46) to the client.

2024-03-29 14:06 UTC, grepfruit19 commented
@beeme1mr Then in terms of this ticket, would you be okay with me un-exposing the provider and holding off on exposing the provider metadata for future work?

2024-03-29 14:15 UTC, beeme1mr commented
> @beeme1mr Then in terms of this ticket, would you be okay with me un-exposing the provider and holding off on exposing the provider metadata for future work?

Sure, no problem at all. Thanks for your work on this PR.

2024-03-29 16:04 UTC, grepfruit19 commented
@beeme1mr I've updated the PR and commented out the corresponding tests

2024-03-29 16:41 UTC, grepfruit19 commented
@beeme1mr I think @maxveldink is out of office today, if this looks good to you mind giving it an approve + merge?

2024-03-29 16:48 UTC, beeme1mr approved these changes

2024-03-29 16:48 UTC, merged